### ISSUE TITLE
perl.prov mistakenly adds embedded Parse::Yapp::Driver

### ISSUE THREAD

**Issue by jirislaby** [rpm-software-management/perl-rpm-packaging#1]
`Math-Calc-Units` uses `Parse::Yapp::Driver` and contains its generated grammar:
https://metacpan.org/release/SFINK/Math-Calc-Units-1.07/source/Units/Grammar.pm

There is:
```perl
package Math::Calc::Units::Grammar;
use vars qw ( @ISA );
use strict;
 
@ISA= qw ( Parse::Yapp::Driver );
#Included Parse/Yapp/Driver.pm file----------------------------------------
{
#
# Module Parse::Yapp::Driver
#
# This module is part of the Parse::Yapp package available on your
# nearest CPAN
...
 
package Parse::Yapp::Driver;
...
$VERSION = '1.04';
```
`perl.prov` generates:
```
perl(Parse::Yapp::Driver) = 1.04
```
It should likely (somehow) ignore embedded packages. Or at least provide a blacklist feature (to supply `Parse::Yapp::Driver` in this very case).

**Comment by pmatilai** [comment]
Patches welcome.

Until then, use the filtering mechanism(s) available: https://rpm-software-management.github.io/rpm/manual/dependency_generators.html

**Comment by ffesti** [comment]
Those generators are something we would happily hand over to a Perl community maintained perl-rpm-macros package.

See also #2747

**Comment by stoecker** [comment]
For openSUSE we use patches which change source so that it's no longer detected (usually with a line break or similar). That's ugly and thus never reported upstream. Maybe we can add a keyword for these cases (like **# no-rpm-provides**) which upstream authors would accept?

**Comment by perlpunk** [comment]
Like mentioned, using a linebreak
```
package
  Foo;
```
is the common way to ignore packages; that's also how the CPAN indexer works.

If a module specifies a package and even specifies a version for it, it looks like it really intended to provide the package.
Otherwise it looks like Math-Calc-Units should have rather been using a subclass here (didn't have a closer look).

The modern way is to list all provided packages in the `META.(json|yml)`
